name       : mypaint-brushes
version    : 2.0.2
release    : 5
source     :
    - https://github.com/mypaint/mypaint-brushes/releases/download/v2.0.2/mypaint-brushes-2.0.2.tar.xz : 7984a74edef94571d872d0629b224abaa956a36f632f5c5516b33d22e49eb566
homepage   : https://github.com/mypaint/mypaint-brushes
license    :
    - CC0-1.0
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Brushes to be used with the MyPaint library
description: |
    Brushes used by MyPaint and other software using libmypaint.
patterns   : /usr/share/pkgconfig/mypaint-brushes-2.0.pc
rundeps    :
    - libmypaint
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
