name       : mypaint-brushes
version    : 1.3.0
release    : 1
source     :
    - https://github.com/Jehan/mypaint-brushes/archive/v1.3.0.tar.gz : 704bb6420e65085acfd7a61d6050e96b0395c5eab078433f11406c355f16b214
license    :
    - CC0-1.0
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Brushes to be used with the MyPaint library
description: |
    Brushes used by MyPaint and other software using libmypaint.
patterns   : /usr/share/pkgconfig/mypaint-brushes-1.0.pc
rundeps    :
    - libmypaint
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
